# Generated by Django 4.2.3 on 2023-09-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.TextField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('insight', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('start_year', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('added', models.TextField(blank=True, null=True)),
                ('published', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
